# Generated by Django 4.0.6 on 2022-08-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210529_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25, verbose_name='Firstname')),
                ('lastname', models.CharField(max_length=25, verbose_name='Lastname')),
                ('email', models.EmailField(max_length=50, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=15, null=True, verbose_name='Phone #')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
