# Generated by Django 4.0.6 on 2022-08-13 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_contact_alter_order_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact_Us',
        ),
    ]
