# Generated by Django 4.0.6 on 2022-08-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_contact_contact_us'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_us',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='email',
            field=models.EmailField(max_length=250, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='firstname',
            field=models.CharField(max_length=50, verbose_name='Firstname'),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='lastname',
            field=models.CharField(max_length=50, verbose_name='Lastname'),
        ),
    ]
