# Generated by Django 4.0.6 on 2022-08-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_contact_us_options_alter_contact_us_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='firstname',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='lastname',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='phone',
            field=models.CharField(max_length=15, null=True, verbose_name='Phone Number'),
        ),
    ]
