# Generated by Django 4.0.6 on 2022-09-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_contact_us_firstname_alter_contact_us_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='United States', max_length=150, verbose_name='Country'),
        ),
    ]
